### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas.core.config'

### ISSUE THREAD

**Issue by ministp** [aliyun/aliyun-odps-python-sdk#100]
pandas 升级到0.25.0版本，引发异常
依赖pandas包存在的问题
报错信息如下：
from pandas.core.config import OptionError as PandasOptionError

网上搜了下：
是pandas升级了，odps依赖项目也变了
[pandas.set_option — pandas 0.25.0 documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.set_option.html  )

问题: 你们会更新吗？

**Comment by qinxuye** [comment]
有个 PR 正在做：https://github.com/aliyun/aliyun-odps-python-sdk/pull/99。

**Comment by ministp** [comment]
谢谢

**Comment by prestow** [comment]
请我有进展了吗？

**Comment by qinxuye** [comment]
本周会发版本修复。

**Comment by VicTangg** [comment]
I encounter the same issue today. Meanwhile, a interim fix for this problem is to pip install 'pandas==0.24.2' or versions older than 0.25.0.

**Comment by wjsi** [comment]
Already fixed in https://github.com/aliyun/aliyun-odps-python-sdk/commit/ae65e3f5efddb2e5fa85291844f2cc284c8b530a

**Comment by lli27** [comment]
我有一个类似的问题。第三方Python包作为资源上传到MaxCompute后，如何更新版本呢？我上传0.18版本的sklearn包到MaxCompute上后，运行from sklearn.preprocessing._encoders import OrdinalEncoder出错，查看源代码，发现这个版本没有这个函数，所以我用drop resource sklearn.zip的方法删除这个资源。但import sklearn还是成功，这是为什么？所以我重新add archive sklearn.zip, 这个是0.21版本的sklearn, 但运行print(sklearn.__version__)==0.18.就是说删除资源，也没有将原来的sklearn卸载掉，上传最新的版本，运行时使用的还是老版本。
