### ISSUE TITLE
第三方python包上传到maxcompute后, 如何更新版本？

### ISSUE THREAD

**Issue by lli27** [aliyun/aliyun-odps-python-sdk#102]
我上传0.18版本的sklearn包到MaxCompute上后，运行from sklearn.preprocessing import OrdinalEncoder出错，查看源代码，发现这个版本没有这个函数，所以我用drop resource sklearn.zip的方法删除这个资源。但import sklearn还是成功，这是为什么？所以我重新add archive sklearn.zip, 这个是0.21版本的sklearn, 但运行print(sklearn.version)==0.18.就是说删除资源，也没有将原来的sklearn卸载掉，上传最新的版本，运行时使用的还是老版本。

**Comment by wjsi** [comment]
Please consult support team for usage problems.
