### ISSUE TITLE
英文版文档需更新

### ISSUE THREAD

**Issue by alvinyeats** [aliyun/aliyun-odps-python-sdk#109]
英文版，https://pyodps.readthedocs.io/en/latest/base-tables.html
![image](https://user-images.githubusercontent.com/9098011/71148628-16570900-2267-11ea-9b90-f95bc1cce6bb.png)

中文版， https://pyodps.readthedocs.io/zh_CN/latest/base-tables.html
![image](https://user-images.githubusercontent.com/9098011/71148672-3f779980-2267-11ea-998e-40b48e1fb57f.png)

github
![image](https://user-images.githubusercontent.com/9098011/71148437-b2344500-2266-11ea-9046-0aac447f71e7.png)

**Comment by wjsi** [comment]
Fixed in v0.11.3. Thanks for the report.
