### ISSUE TITLE
过滤数据，string类型怎么处理呢？

### ISSUE THREAD

**Issue by skyue** [aliyun/aliyun-odps-python-sdk#11]
wiki上的例子都是数字过滤，涉及string如何处理。
我把日期也直接存为了string，比如「20161123」，如何选择这一天的记录？

update:
改用filter方法，提示「keyword can't be an expression」

`org.filter(org.product='vt_finance', org.day='20161122', hour='23').head(5)`

**Comment by skyue** [comment]
自己折腾出来了，原来就是按pandas处理，初学者，不熟。。

**Comment by Cheonsoon** [comment]
@skyue hi，咨询一下，string类型like过滤如何处理呢？我按照 http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.filter.html?highlight=filter#pandas.DataFrame.filter 好像也没有试出来额

**Comment by Cheonsoon** [comment]
@skyue 哈哈，搞定，初玩pandas，完全不会，http://stackoverflow.com/questions/31254738/how-to-filter-pandas-dataframe-by-string 这样解决了。。

**Comment by chineking** [comment]
df.field.contains('sth')

**Comment by Cheonsoon** [comment]
对对对对对，谢谢谢谢啦~~

**Comment by chineking** [comment]
pandas的问题不要到我们的issue下面来问问题哈。

**Comment by Cheonsoon** [comment]
好拔拔😊😊
