### ISSUE TITLE
Datetime range

### ISSUE THREAD

**Issue by liyiheng** [aliyun/aliyun-odps-python-sdk#110]
OverflowError: can't convert negative value to uint64_t
```py
# Column(name='dt_before_1970', type='datetime')
record['dt_before_1970'] = '1966-06-06 00:00:00'
writer.write(record)
```
https://github.com/aliyun/aliyun-odps-python-sdk/blob/ae65e3f5efddb2e5fa85291844f2cc284c8b530a/odps/tunnel/io/writer_c.pyx#L266-L268

**Comment by wjsi** [comment]
Already fixed in the latest release.
