### ISSUE TITLE
How to convert pyodps dataFrame count() to int64

### ISSUE THREAD

**Issue by mobilestack** [aliyun/aliyun-odps-python-sdk#125]
Since it is a type of odps.df.expr.core.Count, I tried other ways, they just do not work. One works for me, as  `int(repr(df.count()))`, but seems there must be something better, is there?

**Comment by hekaisheng** [comment]
refer to the docs: https://pyodps.readthedocs.io/zh_CN/latest/df-basic.html#id12 .

use `df.count().execute()`.

**Comment by mobilestack** [comment]
> refer to the docs: https://pyodps.readthedocs.io/zh_CN/latest/df-basic.html#id12 .
> 
> use `df.count().execute()`.

 It works, thanks!
