### ISSUE TITLE
TLS certificate not validated

### ISSUE THREAD

**Issue by coffeemakr** [aliyun/aliyun-odps-python-sdk#127]
The TLS certificate validation is disabled in https://github.com/aliyun/aliyun-odps-python-sdk/blob/master/odps/rest.py#L132

Therefore, MITM attacks would be possible. Is there  a reason why it is disabled all the time?

**Comment by wjsi** [comment]
Fixed in v0.11.3 by adding `options.verify_ssl = True`.
