### ISSUE TITLE
使用sdk查看外部表是，直接报错Catalog Service Failed, ErrorCode: -1, Error Message:

### ISSUE THREAD

**Issue by guozhihua12** [aliyun/aliyun-odps-python-sdk#129]
在终端执行是没有问题的。

>>> odps = ODPSService("xx", "xxx", "xx", "http://service.odps.aliyun.com/api")
>>> with o.execute_sql('desc extended datahub_aa_2_external').open_reader() as reader:
...     print(reader.raw)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python3.6.7/lib/python3.6/site-packages/odps/core.py", line 782, in execute_sql
    inst.wait_for_success()
  File "/opt/python3.6.7/lib/python3.6/site-packages/odps/models/instance.py", line 553, in wait_for_success
    raise exc
odps.errors.ODPSError: InstanceId: 20200831083859882gmyhr4pr2
Catalog Service Failed, ErrorCode: -1, Error Message:

**Comment by qinxuye** [comment]
这个实际上不是 SQL。

table.extended_properties 可以看到 extended 属性。

**Comment by guozhihua12** [comment]
我还是想通过execute_sql或者run_sql实现查看表的元数据。
官网的文档是支持这种写法的。https://help.aliyun.com/document_detail/27829.html?spm=a2c4g.11186623.6.645.6a3e6ab9pUCzTG

且我用datawork和终端都是可以执行 'desc extended datahub_aa_2_external' 获取外部表的元数据信息。
还是希望odps维护团队能支持这个功能，谢谢。

**Comment by qinxuye** [comment]
这个东西是 console 端解析的，在客户端解析。所有 SDK 都不支持提交这个 SQL。要支持需要开工单，要求 SQL 支持这个语法。

**Comment by guozhihua12** [comment]
可能不是这个问题，因为内部表的话sdk是可以使用这个命令的。
>>> instance = o.run_sql("desc aa_int;", name='Query_SQL')
>>> instance = o.get_instance(instance.id)
>>> instance.get_task_result(task_name)
'+------------------------------------------------------------------------------------+\n| Owner: RAM$xxxx | Project: xxxx                                 |\n| TableComment:                                                                      |\n+------------------------------------------------------------------------------------+\n| CreateTime:               2020-05-01 15:24:24                                      |\n| LastDDLTime:              2020-05-01 15:24:24                                      |\n| LastModifiedTime:         2020-05-01 15:24:24                                      |\n+------------------------------------------------------------------------------------+\n| InternalTable: YES      | Size: 0                                                  |\n+------------------------------------------------------------------------------------+\n| Native Columns:                                                                    |\n+------------------------------------------------------------------------------------+\n| Field           | Type       | Label | Comment                                     |\n+------------------------------------------------------------------------------------+\n| ds              | bigint     |       |                                             |\n+------------------------------------------------------------------------------------+\n'
>>>

**Comment by qinxuye** [comment]
desc extended，这个 extended 不是指外部表。是指表的扩展属性。desc table 是 SQL 支持的。

这个问题恕不继续回答。
