### ISSUE TITLE
df.head(n) 对于分区列的值均解析为 NoneType

### ISSUE THREAD

**Issue by Cheonsoon** [aliyun/aliyun-odps-python-sdk#13]
直接对分区表执行 df.head(n)，相应分区列debug发现其类型解析正确，但是值均解析为 NoneType；
df._types -> 
![qq20170110-0](https://cloud.githubusercontent.com/assets/1361794/21811280/1c42c384-d78a-11e6-8dde-a8eae0878694.png)
df._values -> 
![qq20170110-1](https://cloud.githubusercontent.com/assets/1361794/21811299/286f0b90-d78a-11e6-8e66-e52a089155e2.png)

如果使用 df['xxx', '分区列'].head(n)，则可解析出相应列和值。

**Comment by chineking** [comment]
OK，这个问题后续会修复。

**Comment by Cheonsoon** [comment]
嗯嗯嗯，好哒好哒，感谢~

**Comment by Cheonsoon** [comment]
老板老板，还发现个问题，就是使用pandas后端作本地调试时，测试用例同上，无论是否显示标明分区列，其值均为None。
继而导致 df = df.groupby('分区列').agg(df.profit.min(), df.profit.max()) 在pandas后端下返回为 'Empty DataFrame' 【这个也许是我使用上的问题，还望指教~】

**Comment by chineking** [comment]
OK，这个我们会一起看下

**Comment by chineking** [comment]
问题已经修复，``pip install -U pyodps`` 更新

**Comment by Cheonsoon** [comment]
哦哦哦哦哦，好的好的。O(∩_∩)O谢谢
