### ISSUE TITLE
使用desc方法查看外部表，报错Parameter PanguFullPath must be a pangu full address

### ISSUE THREAD

**Issue by guozhihua12** [aliyun/aliyun-odps-python-sdk#130]
>>> instance = o.run_sql("desc aa_2_external;", name='Query_SQL')
>>> instance.get_task_result(task_name)
'Parameter PanguFullPath must be a pangu full address.'
>>>

**Comment by qinxuye** [comment]
错误和 PyODPS 本身无关，请开工单询问。
