### ISSUE TITLE
sqlalchemy集成支持不完善，没有executemany方法

### ISSUE THREAD

**Issue by leeming87v5** [aliyun/aliyun-odps-python-sdk#136]
重现方法：
db.session.add(user_1)
db.session.add(user_2)
db.session.commit()

报错信息：
  File "**********************/sqlalchemy/engine/default.py", line 587, in do_executemany
    cursor.executemany(statement, parameters)
AttributeError: 'Cursor' object has no attribute 'executemany'

**Comment by wjsi** [comment]
Already fixed.
