### ISSUE TITLE
core.py中的 __getstate__ 导致 [Kite](https://www.kite.com/) 无法提示 odps的方法

### ISSUE THREAD

**Issue by albin3** [aliyun/aliyun-odps-python-sdk#138]

**Comment by albin3** [comment]
v0.9.1 可以自动提示
![image](https://user-images.githubusercontent.com/6190670/102608417-cdc97880-4164-11eb-8f3d-fe6d593f2bfc.png)

v0.9.3无法自动提示
![image](https://user-images.githubusercontent.com/6190670/102608550-036e6180-4165-11eb-89f4-ec5cd9c7e550.png)

**Comment by albin3** [comment]
![image](https://user-images.githubusercontent.com/6190670/102608684-37e21d80-4165-11eb-81d4-98830f2c95bf.png)

**Comment by wjsi** [comment]
Not valid for the latest release of PyODPS under Jupyter Lab.
