### ISSUE TITLE
关于 str.replace 不被内置函数支持的问题

### ISSUE THREAD

**Issue by Cheonsoon** [aliyun/aliyun-odps-python-sdk#14]
现在想用 str.replace 正则替换，但是发现 compile 出来的SQL是带 pyodps_udf_xxxx 的，于是跟踪源码发现，strings.Replace 确实没在 compiler 中实现。
目前发现 strings.Contains 是实现了内部函数以及正则，于是想参考实现 strings.Replace，但是发现补充 elif 后打断点程序并不会执行（不会进入 visit_string_op ）。跟了一下代码，但还是不清楚哪儿有问题，麻烦指导一下子，谢谢~

**Comment by chineking** [comment]
dataframe在compile之前，会有个analyze的过程，代码在：https://github.com/aliyun/aliyun-odps-python-sdk/blob/master/odps/df/backends/odpssql/analyzer.py#L607

由于Python的正则和MaxCompute的正则不相同，为了保证和Python正则的兼容性，这里在analyzer里会被改写成自定义函数，在里面调用Python正则来替换。

现在这么写是报错不支持Python UDF吗？

**Comment by chineking** [comment]
contains这里其实应该是有问题的，应该也会有正则不一致的情况。这里应该也是要和replace是一样的处理方式。

现在，要想对一列调用MaxCompute内建函数，只能：

```
df.field.map('regexp_replace', '**your pattern**', '**your replace string**')
```

**Comment by Cheonsoon** [comment]
哦哦哦，好的好的，我跟跟 analyzer 的相关代码看看~
唉，是啊，估计是因为我这边用得是odps的公共服务，没法用python的udf吧。map的话好像也得用到udf，我们索性重写一下replace算了😂😂

**Comment by chineking** [comment]
这个应该不是bug。先close。
