### ISSUE TITLE
DataFrame sample parse exception

### ISSUE THREAD

**Issue by crowsad** [aliyun/aliyun-odps-python-sdk#140]
Hi, thanks for the great package.

I want to sample my table to n rows before I read them, so far what I did is.

```python
df_t = t.to_df()
df_t = df_t.sample(n=10000).to_pandas()
```

but it gives this error

```
OtherError:ODPS-0130161:[1,213] Parse exception - invalid token ','
ODPS-0130161:[1,522] Parse exception - invalid token ')'
```

when i try using `parts` instead of `n` its working just fine, but that is not quite what i want. is there anything wrong on my side? or can you give another way to do sampling instead of what i did here?

**Comment by wjsi** [comment]
Currently sampling with counts depends on PAI commands which are not always available. We are now working on a new version of DataFrame more compatible with pandas and this issue will be resolved then.
