### ISSUE TITLE
Consider uploading the ipywidget bundle to a CDN

### ISSUE THREAD

**Issue by DonJayamanne** [aliyun/aliyun-odps-python-sdk#143]
Please could you consider uploading the widget bundle to one of the following CDNs:
* jsdelivr
* unpkg

Most ipywidget authors publish their widget bundles to one of these.
This helps widgets work in non-jupyter contexts such as voila, vscode, etc.

Original issue https://github.com/microsoft/vscode-jupyter/issues/4971

**Comment by wjsi** [comment]
Close as stale.
