### ISSUE TITLE
异步执行sql，如何像同步执行sql那样获取结果？

### ISSUE THREAD

**Issue by daidai21** [aliyun/aliyun-odps-python-sdk#147]
![image](https://user-images.githubusercontent.com/36124626/112985818-40e68000-9193-11eb-8695-4407af03d3cc.png)

https://pyodps.readthedocs.io/zh_CN/latest/base-sql.html

**Comment by hekaisheng** [comment]
instance.open_reader(), 同步接口返回的也是 instance 对象

**Comment by daidai21** [comment]
感谢
