### ISSUE TITLE
【问题】 执行sql读取record是结果已经全部回传到client了才开始for循环还是？

### ISSUE THREAD

**Issue by daidai21** [aliyun/aliyun-odps-python-sdk#149]
```py
with o.execute_sql('select * from dual').open_reader() as reader:
     for record in reader:
         # 处理每一个record
```
在`for record in reader:`执行之前readerclient已经得到了所有数据吗还是  在执行`处理每一个record`的时候一条一条数据是client从server拉取的？

需求：
是想使用ODPS的sql 判断字段是否是枚举字段 然后如果是枚举字段获取枚举值list

计算字段的group by，设置阈值，如果枚举值超过100则认定字段是非枚举字段

我想的是，sql group by非枚举字段，按行迭代，有个set记录已经迭代过的字段值，其实如果枚举值已经有100了，就不用再往下计算了；主要是数据量是PB级别，或者百亿以上， sql group by非枚举字段太费资源了

有什么解决办法吗？

感谢

**Comment by hekaisheng** [comment]
有一个 stream reader 去流式读取，不会都拉取到本地

**Comment by daidai21** [comment]
![image](https://user-images.githubusercontent.com/36124626/115179235-71bc3400-a105-11eb-9927-d188fa9ae552.png)

这个吗？

**Comment by hekaisheng** [comment]
直接执行 groupby agg 看最后结果的行数不行吗，reader.count 就是结果的行数

**Comment by daidai21** [comment]
> 直接执行 groupby agg 看最后结果的行数不行吗，reader.count 就是结果的行数

`iris.groupby('name').agg(iris.petallength.notnull().sum())` 这样，实际是 py -> ast -> sql， 实际执行的还是SQL呀

示例代码：
```py
from odps.examples.tables import create_iris
from odps.df import DataFrame
from odps.config import options

options.interactive = True
options.verbose = True

iris = create_iris(o, "asd")

iris_df = DataFrame(iris)

print(iris_df.head(5))

# print(iris_df[iris_df.sepal_width < 4].head(3))


print(iris_df.groupby('sepal_width').agg(iris_df.petal_length.notnull().sum()))

```

生成的sql：

```sql
CREATE TABLE tmp_pyodps_944d369b_f224_4dab_957c_d0f6f9782d88 LIFECYCLE 1 AS 
SELECT t1.`sepal_width`, SUM(IF(t1.`petal_length` IS NOT NULL, 1, 0)) AS `petal_length_sum` 
FROM chaos_dev.`asd` t1 
GROUP BY t1.`sepal_width`;

```

**Comment by hekaisheng** [comment]
你那样很多情况下还没有 sql 来得快，当然通过 download 表数据也可以，自己取舍吧

**Comment by daidai21** [comment]
> 你那样很多情况下还没有 sql 来得快，当然通过 download 表数据也可以，自己取舍吧

嗯嗯，（表太大了，PB级别）我自己测测试试

感谢！！
