### ISSUE TITLE
pyodps sdk支持编写udf吗

### ISSUE THREAD

**Issue by haijohn** [aliyun/aliyun-odps-python-sdk#15]
在maxCompute的文档里只有JAVA的udf。我在pyodps的sdk里看到可以编写自定义的函数，但是没有看到具体接口实现的文档。

**Comment by chineking** [comment]
公共云因为安全问题，暂未开放Python UDF。

**Comment by haijohn** [comment]
有没有开放Python UDF的计划

**Comment by chineking** [comment]
这个短期内还没有，要看安全方面的进度。

后续有进展我会同步。
