### ISSUE TITLE
[New Feature] DataFrame存储空间优化

### ISSUE THREAD

**Issue by daidai21** [aliyun/aliyun-odps-python-sdk#155]
我看使用DataFrame转sql产生的中间表都是`create table ... lifecycle 1 as select ...`, 但是运行完后并未删除这个中间表，其实这个中间表已经没用了，是否可以优化下呢？
毕竟大表的话还是比较占空间的。

**Comment by hekaisheng** [comment]
lifecycle 为 1，会自动回收的

**Comment by daidai21** [comment]
我知道lifecycle 为 1会回收的，但是当时1d内的话存储空间还是占用的释放不了呀

**Comment by wjsi** [comment]
We will not add new features to PyODPS DataFrame. Try using MaxFrame if possible and it provides more flexible lifecycles for intermediate tables.
