### ISSUE TITLE
python3.5 jupter nootbook:  from odps import ODPS AttributeError: 'NoneType' object has no attribute 'DOMWidget'

### ISSUE THREAD

**Issue by aohan237** [aliyun/aliyun-odps-python-sdk#16]
in python3.5 virtualenv  
  160 else:
    161     if in_ipython_frontend():
--> 162         class InstancesProgress(widgets.DOMWidget):
    163             _view_name = build_trait(Unicode, 'InstancesProgress', sync=True)
    164             _view_module = build_trait(Unicode, 'pyodps/progress', sync=True)

AttributeError: 'NoneType' object has no attribute 'DOMWidget'

**Comment by chineking** [comment]
应该是缺少了ipywidgets，又包含jupyter.

pip install -U jupyter

**Comment by aohan237** [comment]
嗯，刚刚发现是这个问题，升级后可以正常使用了。谢谢
