### ISSUE TITLE
@annotate入参类型解析问题

### ISSUE THREAD

**Issue by desperatedog** [aliyun/aliyun-odps-python-sdk#163]
@annotate('array<map<string, string>> -> string')
解析入参调用_get_types(types)方法的时候，直接通过types.split(',')来分割导致报错了，是不支持array套map吗，还是bug？

**Comment by patterson163** [comment]
@desperatedog @lyman @qinxuye 我也遇到这个问题了。在maxcompute Studio里，目前看是可以下载到的pyodps包中，不支持其他数据类型。还是按照低版本MC支持的数据类型（bigint,string,datetime,boolean,double,*）工作的。
![IMG_20230616_143132](https://github.com/aliyun/aliyun-odps-python-sdk/assets/8038998/9ec4397d-a1ad-4253-b596-61c38b7a67ba)

**Comment by patterson163** [comment]
> @Annotate('array<map<string, string>> -> string') 解析入参调用_get_types(types)方法的时候，直接通过types.split(',')来分割导致报错了，是不支持array套map吗，还是bug？

可是mc上运行嵌套的，udf很好使啊，就是不能本地调试。有点费解了

**Comment by wjsi** [comment]
> > @Annotate('array<map<string, string>> -> string') 解析入参调用_get_types(types)方法的时候，直接通过types.split(',')来分割导致报错了，是不支持array套map吗，还是bug？
> 
> 可是mc上运行嵌套的，udf很好使啊，就是不能本地调试。有点费解了

pyou 用的 csv 输入，没法支持复杂类型（毕竟 array / map 里面自己就有逗号），这个我们要研究一下要怎么搞，估计没那么快

**Comment by wjsi** [comment]
可使用最新 maxcompute studio 及 pyodps>=0.12.0。
