### ISSUE TITLE
odps cumsum函数与python中cumsum函数结果不一致

### ISSUE THREAD

**Issue by Apple9** [aliyun/aliyun-odps-python-sdk#168]
针对arr = np.array([1,2,3],[4,5,6])
python groupby后cusum结果[1,2,3],[5,7,9]
而
odps2中groupby后cumsum结果为[5,7,9],[5,7,9]，
1、请问是什么原因
2、如果我想达到和python一样的效果，有什么办法实现

**Comment by wjsi** [comment]
Not PyODPS issue.
