### ISSUE TITLE
module 'IPython.utils.io' has no attribute 'IOStream'

### ISSUE THREAD

**Issue by seamancode** [aliyun/aliyun-odps-python-sdk#173]
Python version 3.9

**Comment by xdanger** [comment]
+1

**Comment by angelwhu** [comment]
+1

**Comment by elenazadnepr** [comment]
+1

**Comment by hekaisheng** [comment]
It has some compatibility issues for Python3.9 now, Python 3.7 is recommended version.

**Comment by elenazadnepr** [comment]
My teammate is using Python 3.10.1, and pyodps works fine for him

**Comment by wjsi** [comment]
Already fixed on v0.11.0.
