### ISSUE TITLE
用pickle加载模型时候报错attributeError: Unpickler instance has no attribute 'persistent_load'

### ISSUE THREAD

**Issue by zhongsheng-chen** [aliyun/aliyun-odps-python-sdk#176]
我在本地训练模型，然后将调用udf函数应用模型进行预测:

def predictor():
       with get_cache_file('model.zip') as fname:
             clf = pickle.load(fname)
return clf

报错：attributeError: Unpickler instance has no attribute 'persistent_load'

本地和服务器python都是2.7.8

sklearn的版本都是0.20.0

**Comment by wjsi** [comment]
Please ask consult team of MaxCompute for UDF questions.

**Comment by GitHubwwZ** [comment]
> 我在本地训练模型，然后将调用udf函数应用模型进行预测:
> 
> def predictor(): with get_cache_file('model.zip') as fname: clf = pickle.load(fname) return clf
> 
> 报错：attributeError: Unpickler instance has no attribute 'persistent_load'
> 
> 本地和服务器python都是2.7.8
> 
> sklearn的版本都是0.20.0

请问问题解决了吗？通过什么方式解决的报错呀？
