### ISSUE TITLE
Decoder有性能问题

### ISSUE THREAD

**Issue by torshie** [aliyun/aliyun-odps-python-sdk#180]
decoder_c.pyx这个文件里实现的Decoder有性能问题

所有的`get_varint32，get_varint64`函数都会调用到utils_c.pyx里面的 `read_input_byte()`，最终回到 `Decoder.read(1)`，然后到`SimpleInputStream.read(1)`：
`get_varint32() -> read_input_byte() -> Decoder.read(1) -> SimpleInputStream.read(1)` 这个链路最后一个环节如果大量调用会产生性能问题。

修改方法：
* 一次性从`SimpleInputStream`里读取一整块内存
* 在`Decoder` 保存整个内存块对应的`bytes`对象，同时用一个`char*`来跟踪这个内存块的使用情况
* `read_input_byte()`通过上面所说的`char*`来读取单个字节，这样在解析数据的时候就不会回到python解释器里去，而是停留在静态编译的C代码里，一个整数读取完后才会回到python解释器里去

下面是`snakeviz`的截图，可以看出读取数据时大部分时间花在`SimpleInputStream.read()`上面：
![image](https://user-images.githubusercontent.com/1214465/176580289-c4207c8f-9cbc-484c-ac9f-8bebc82bcd5f.png)

**Comment by wjsi** [comment]
Fixed in v0.11.1 release.
