### ISSUE TITLE
odps.errors.ODPSError: 504

### ISSUE THREAD

**Issue by situjunhao** [aliyun/aliyun-odps-python-sdk#182]
odps.errors.ODPSError: 504: <!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
<p><em>Faithfully yours, tengine.</em></p>
</body>
</html>

发生这样的错误，得怎么处理？

**Comment by wjsi** [comment]
Server side error.
