### ISSUE TITLE
Setup odps.sql.hive.compatible=true on sqlalchemy queries

### ISSUE THREAD

**Issue by Menniti** [aliyun/aliyun-odps-python-sdk#189]
Hello @wjsi 

I`m having issues query into maxcompute, because i can`t pass the parameter > 'odps.sql.hive.compatible=true'

![image](https://user-images.githubusercontent.com/15658494/187799712-987e9c13-eaab-4d1d-864c-ba898e441f7b.png)

Do you have any idea how I can overcome this issue ?

Thanks

**Comment by wjsi** [comment]
Already supported in v0.11.3. Docs added at https://pyodps.readthedocs.io/zh_CN/latest/base-sqlalchemy.html#id1.
