### ISSUE TITLE
SAWarning: Dialect odps:rest will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.

### ISSUE THREAD

**Issue by dale-di** [aliyun/aliyun-odps-python-sdk#193]
sqlAlchemy == 1.4.32
查询时报错：
/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:1402: SAWarning: Dialect odps:rest will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Dialect maintainers should seek to set this attribute to True after appropriate development and testing for SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  return self.connectable.execution_options().execute(*args, **kwargs)

**Comment by wjsi** [comment]
Warning suspended in v0.11.3.
