### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by dameassz** [aliyun/aliyun-odps-python-sdk#200]
在内网电脑下载本机安装odps和pyodps的whl后，pip list查看odps和pyodps均安装成功。
但在jupyter执行import odps或者from odps import ODPS都会如下报错：
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-2c4753f68c85> in <module>()
----> 1 import odps

D:\Anaconda3\lib\site-packages\odps\__init__.py in <module>()
     22 
     23 from .config import options
---> 24 from .core import ODPS
     25 from .df import DataFrame, Scalar, RandomScalar, NullScalar
     26 from .inter import setup, enter, teardown, list_rooms

D:\Anaconda3\lib\site-packages\odps\core.py in <module>()
     22 import weakref
     23 
---> 24 from . import models, accounts, errors, utils
     25 from .compat import six, Iterable
     26 from .config import options

D:\Anaconda3\lib\site-packages\odps\models\__init__.py in <module>()
     15 # limitations under the License.
     16 
---> 17 from .core import RestModel
     18 from .projects import Projects
     19 from .project import Project

D:\Anaconda3\lib\site-packages\odps\models\core.py in <module>()
     17 import warnings
     18 
---> 19 from .. import options, serializers, utils
     20 from ..compat import six, quote_plus
     21 from .cache import cache, del_cache

D:\Anaconda3\lib\site-packages\odps\serializers.py in <module>()
     23 import requests
     24 
---> 25 from . import compat, utils
     26 from .compat import BytesIO, ElementTree, PY26, six
     27 from .utils import to_text

D:\Anaconda3\lib\site-packages\odps\utils.py in <module>()
     56     pytz = None
     57 try:
---> 58     from odps.src.utils_c import CMillisecondsConverter
     59 except ImportError:
     60     CMillisecondsConverter = None

D:\Anaconda3\lib\site-packages\odps\src\utils_c.pyx in init odps.src.utils_c()

OSError: [Errno 22] Invalid argument

**Comment by dameassz** [comment]
Anaconda的python版本是3.6.4
odps版本是（3.5.1）
pyodps版本是（0.11.3.1）

**Comment by wjsi** [comment]
Cannot get the same error under Python 3.6 under either x86 or x64 architecture, either under Windows 7 or Windows 11. Please provide more information about the version of your host operating system and its architecture.

**Comment by wjsi** [comment]
Possibly related with [bpo-29097](https://bugs.python.org/issue29097). Use Python 3.6.7 or later to resolve this isue.

**Comment by wjsi** [comment]
Workaround added in v0.11.4 release.
