### ISSUE TITLE
udtf中无法读取zip资源

### ISSUE THREAD

**Issue by funicia** [aliyun/aliyun-odps-python-sdk#201]
from odps.udf import annotate
from odps.udf import BaseUDTF
import sys
import os

import zipfile

@annotate('bigint,string->*')
class ExtratClaimJson(BaseUDTF):
    def __init__(self):
        sys.path.insert(0, 'work/xxx.zip')
     def process(self, claim_id, js): 
        self.forward(str(zipfile.is_zipfile("xxx.zip")), str(zipfile.is_zipfile("work/xxx.zip")))

其中xxx.zip已经上传到maxcompute资源中。

返回值为False，非zip文件。

但是在pyodps3节点下是可以读取到这个zip文件的

**Comment by wjsi** [comment]
Please consult supporting team of MaxCompute. Issues are not places for general usage questions.
