### ISSUE TITLE
SQL结果数据太多如何处理？

### ISSUE THREAD

**Issue by einvince** [aliyun/aliyun-odps-python-sdk#21]
SQL结果数据限制10000条，有什么好办法全部拿到结果数据

**Comment by chineking** [comment]
现在可以使用 instance tunnel，open_reader加入两个选项。PyODPS 需要至少 0.7.2 版本

```
with o.execute_sql().open_reader(use_tunnel=True, limited_enabled=False) as reader:
    # 处理一样
```

文档中有相关叙述：http://pyodps.readthedocs.io/zh_CN/latest/base-sql-zh.html#id5

**Comment by einvince** [comment]
limited_enabled=False，这个不起作用，还是有限制
options.tunnel.limited_instance_tunnel 设为 False 则可以

**Comment by chineking** [comment]
抱歉，是 `limit_enabled=False`
