### ISSUE TITLE
使用pyodps-pack打包第三方包的时候，加--exclude参数就会报错

### ISSUE THREAD

**Issue by joke2003** [aliyun/aliyun-odps-python-sdk#212]
不加--exclude参数没有问题，加上就报错

Windows 10 64位 有Docker Desktop环境

[log.txt](https://github.com/aliyun/aliyun-odps-python-sdk/files/12644249/log.txt)

**Comment by wjsi** [comment]
Caused by mishandling of \r\n endings. Will fix under 0.11.5.

**Comment by wjsi** [comment]
Already fixed with v0.11.5.beta1.
