### ISSUE TITLE
如何利用非docker模式打包依赖包

### ISSUE THREAD

**Issue by HarrisonLee-zh** [aliyun/aliyun-odps-python-sdk#215]
Windows使用--without-docker参数打包依赖包时出现问题，无法正常打包，能否打包本地存在的包，而不是网络远程下载

**Comment by wjsi** [comment]
Won't support that. Please use `-i` option to specify a faster mirror and try Docker mode if your problem still exists.

**Comment by charlie2w** [comment]
远程镜像下载tensorflow时，如何指定tensorflow的python版本、windows版等信息
