### ISSUE TITLE
统计文档问题

### ISSUE THREAD

**Issue by sunyinglong** [aliyun/aliyun-odps-python-sdk#22]
1.odps.ml.statistics 文档中很多方法没有具体的例子，同时没给出相关的return的值，在使用过程中并不友好，希望各位大神增添相关的文档，调用更加清楚。
2.请教一下各位大神，odps.ml中 是否直接就是和PAI一套的计算框架

**Comment by chineking** [comment]
1、我们收到了你的建议，会改进相关文档
2、odps ml底层**目前使用pai实现** ，它可以和我们的DataFrame集成，提供类似pandas+scikit-learn的体验，当然我们有些地方还做的不够好。

**Comment by aabbiiL** [comment]
'AttributeDict' object has no attribute 'notebook_repr_widget'  
请问下怎么样才能使用交互式图表？

**Comment by chineking** [comment]
进度条有显示吗？如果没有运行命令：

```
jupyter nbextension enable --py widgetsnbextension
```

看下有没有效果

**Comment by aabbiiL** [comment]
一开始没用进度条 运行命令后有了 但是依然没有图表

**Comment by chineking** [comment]
似乎是新版本的 jupyter 里组件的问题，我们要确认下，有进展了在这个 session 下更新
