### ISSUE TITLE
odps.df 操作 odpsSql

### ISSUE THREAD

**Issue by Eric0808** [aliyun/aliyun-odps-python-sdk#23]
请问是否可以用dataframe 执行sql 返回result 为df类型？
例如： DataFrame(o.execute_sql('sql query')),
如果可以是否有示例代码，或者有其他办法

**Comment by chineking** [comment]
reader可以转化成pandas DataFrame。

```
with o.execute_sql('your_sql').open_reader() as reader:
    pd_df = reader.to_pandas()
```

pandas DataFrame就可以直接转PyODPS DataFrame。

```
from odps.df import DataFrame

df = DataFrame(pd_df)
```

但这些的前提，是把SQL的结果取到本地。如果想让PyODPS DataFrame远程操作SQL的执行结果，则需要使用 `create table as`，来将这个SQL的结果创建为表。

```
table_name = 'your_table_name'
o.execute_sql('create table %s as %s' % (table_name, your_sql))
df = o.get_table(table_name').to_df()
```

**Comment by Eric0808** [comment]
@chineking 非常感谢您的回复！
