### ISSUE TITLE
pyodps 比 在data-ide web界面上执行相同的操作要快

### ISSUE THREAD

**Issue by Eric0808** [aliyun/aliyun-odps-python-sdk#25]
pyodps 比 在data-ide web界面上执行相同的操作要快
比如：tb.head(10)和 select * from tb limit 10;
请问除了web上有queueing的时间之外；两者集群调度，计算资源上有什么区别吗？

**Comment by chineking** [comment]
df.head 有可能使用的是tunnel接口，这个可以看 http://pyodps.readthedocs.io/zh_CN/latest/df-debug-instruction-zh.html#pandas

你说的 select 理论上应该也是很快的，这个不需要经过调度。
