### ISSUE TITLE
endpoint参数含义？

### ISSUE THREAD

**Issue by d2Code** [aliyun/aliyun-odps-python-sdk#27]
初始化时（示例代码如下），`endpoint`是什么意思？如果可能，能否给出详细的解释，谢谢！
```python
from odps import ODPS

o = ODPS('**your-access-id**', '**your-secret-access-key**', '**your-default-project**',
            endpoint='**your-end-point**')
```

**Comment by chineking** [comment]
https://help.aliyun.com/document_detail/34951.html

非**程序bug或者任何开发上的proposal**请不要在Github issue里提，请联系MaxCompute售后或者在阿里云提交工单。
