### ISSUE TITLE
BUG求助

### ISSUE THREAD

**Issue by sunyinglong** [aliyun/aliyun-odps-python-sdk#28]

**Comment by sunyinglong** [comment]
几位大神，在使用的过程中需要一些问题。不知道是PAI平台的问题还是PYODPS的问题，调用特征工程中rf_importance 返回 xflow not found:的错误 
调用pmml中的execute()方法 ，返回error msg: CreateInstance Failed 错误 请各位帮助

**Comment by chineking** [comment]
详细的错误都贴一下。

**Comment by aabbiiL** [comment]
pyodps 里 调用含有 “left join ”的sql会报错？但是odps直接调用就可以
ODPS-0130161:Parse exception - line 2:35 cannot recognize input near 'left' 'join'

**Comment by chineking** [comment]
用的 run_sql 和 execute_sql 吗？如果是，建议你新开一个 issue，不要在别人的 issue 下问不同问题。把 SQL 贴出来。
