### ISSUE TITLE
dataframe命令行和脚本执行结果不同(求助!!!)

### ISSUE THREAD

**Issue by mlpy** [aliyun/aliyun-odps-python-sdk#29]
脚本执行结果:
http://imgur.com/a/U96NG

命令行执行结果:
http://imgur.com/a/U6LLW

脚本中的执行结果显然是不符合要求的, 但是业务处理要在脚本中进行,求教如何让脚本执行结果和命令行相同??(代码完全一致)

**Comment by chineking** [comment]
这个是个常见问题。

原因是 DataFrame 本身是延迟执行的，只有调用 `execute` 等立即执行的方法时，才会触发执行。

为了在交互式环境能方便进行运行，因此我们在检测到是交互式环境时，会在 repr 一个对象时，触发 `execute` 操作。

因此，在非交互式环境

1、如果想让 DataFrame 执行，需要手动调用 `execute` 等方法。
2、如果想让 print 的时候触发执行（相当于调用 `__repr__`），则可以打开 `options.interactive`。

详细文档中其实有说明：http://pyodps.readthedocs.io/zh_CN/latest/df-basic-zh.html#df-delay-execute

**Comment by mlpy** [comment]
问题解决了，谢谢大佬！！
总结一下解决此问题的两种办法：
①让 print 的时候触发执行（相当于调用 __repr__）。添加如下两行代码：
from odps import options
options.interactive = True
②在待打印的对象或方法后，手动调用.execute()方法，例如：
from odps.df import read_excel
users = read_excel('../test_conf/u.user.xlsx')
print users.execute()
print users.count().execute()
