### ISSUE TITLE
如何同时获取多个分区的数据

### ISSUE THREAD

**Issue by skyue** [aliyun/aliyun-odps-python-sdk#3]
```
with t.open_reader(partition='pt=test') as reader:
```

`partition`这个参数如何设置可以取同一个分区字段的多个分区（或关系）

**Comment by chineking** [comment]
如果你有多个子分区，partition参数需要包括全部字段，比如

```python
with t.open_reader(partition='pt=123,hh=5,mm=3') as reader:
    pass
```

如果只有一级分区，那么需要你自己去获取到下面的子分区，可以通过方法：

```python
for partition in t.iterate_partitions('pt=123'):
    pass
```

再对每个partiton来打开reader

**Comment by chineking** [comment]
哦，我好像理解得不对，你是说的多个值。

那需要对每个值来分别打开reader

**Comment by skyue** [comment]
多谢，了解了。
感觉这样处理不方便，一个分区取多个子值的情况还是非常多的。比如日志文件，常常会用时间做分区，而分析的时候，经常会取一段时间的数据。
希望能增加类似的支持。

**Comment by chineking** [comment]
这个倒是可以封装一层的，但是分区字段怎么样取范围其实很难去划定，因为分区也有可能不是时间有关的。

如果只是分析的话，其实倒是可以不必使用tunnel的。
