### ISSUE TITLE
pyodps.dataframe.value_counts  限制10000条数据？

### ISSUE THREAD

**Issue by aohan237** [aliyun/aliyun-odps-python-sdk#30]
如果我全部采用dataframe接口，如何通过dataframe获取完整的数据？
另外，
open_reader可以采用，limit_enabled=False方法实现，但是也是仅仅一次调用，每次都要配置。

采用enter  空间的做法，进入项目空间。就无法再初始化配置中，直接配置此项配置，源码中，在进入空间中，没有获取options.tunnel.limited_instance_tunnel这项配置，是否考虑添加额外配置，可以允许配置？

**Comment by chineking** [comment]
`value_counts` 限制条数是因为 ODPS 本身排序后必须要限制条数。

可以通过设置

```
from odps import options

options.df.odps.sort.limit = 100000000

**Comment by chineking** [comment]
设置这个值到一个比较大的数值来解决。目前这个值默认是 10000。

**Comment by chineking** [comment]
另外你的需求是 room 支持保存 options 配置？

**Comment by aohan237** [comment]
原来是因为排序问题。 谢谢！

对啊，如果能保持配置，我配置一次，后面就不用配置了，而且每一个空间都可以有不同的配置，不是很方便么

**Comment by chineking** [comment]
这个建议可以考虑下，我们后续看看怎么做。

**Comment by hengqujushi** [comment]
from odps import options

options.df.odps.sort.limit = 100000000

报错如下：
AttributeError: 'AttributeDict' object has no attribute 'odps'
pyodps更新到最新版本

**Comment by hengqujushi** [comment]
10000这个非常坑啊，为什么没在文档里写明呢，对使用者会有很多问题的，非常非常坑。

**Comment by chineking** [comment]
from odps import __version__

看下版本

@hengqujushi

**Comment by hengqujushi** [comment]
升级到最新版好了，但是强烈建议，在文档里注明10000这个限制。

**Comment by chineking** [comment]
http://pyodps.readthedocs.io/zh_CN/latest/df-sort-distinct-apply-zh.html#id2

更新了下文档，check 下 @hengqujushi

**Comment by hengqujushi** [comment]
感谢及时的反馈和回复！
