### ISSUE TITLE
odps-sdk在python3.6的环境下运行报错

### ISSUE THREAD

**Issue by wsYdd** [aliyun/aliyun-odps-python-sdk#33]
错误如下图
![image](https://user-images.githubusercontent.com/11494521/29708661-10ed6ad6-89bc-11e7-838c-7d3fd9f0dfef.png)

**Comment by chineking** [comment]
稍等，正准备发版本，新版本会修复这个问题

**Comment by chineking** [comment]
0.7.10 已经发布，可以验证下问题是否还在。

**Comment by chineking** [comment]
@wsYdd 验证过了没？
