### ISSUE TITLE
如何通过odps.df.DataFrame 写入odps的table

### ISSUE THREAD

**Issue by qbj10** [aliyun/aliyun-odps-python-sdk#35]
如果通过 pandas.Dataframe生成一个 odps.df.DataFrame,
无法通过persist 写table
目前看是找不到对应engine, 没有entrance, 有什么办法可以指定project吗?

**Comment by chineking** [comment]
上传 pandas DataFrame 到 ODPS 时报错：ODPSError: ODPS entrance should be provided
---------------------------------------------------------------------------------------------------

原因是没有找到全局的ODPS入口，有三个方法：

- 使用 [room 机制](http://pyodps.readthedocs.io/zh_CN/latest/interactive-zh.html#cl) ，``%enter`` 的时候，会配置全局入口
- 对odps入口调用 ``to_global`` 方法
- 使用odps参数，``DataFrame(pd_df).persist('your_table', odps=odps)``

**Comment by qbj10** [comment]
谢谢
关于persist, 为何我在源码里看到的定义是:
persist(self, name, partitions=None, partition=None, lifecycle=None, project=None, **kwargs)

**Comment by chineking** [comment]
这个 odps 参数只对 pandas 后端有效。

这边的 **kwargs 针对具体的后端可能有一些额外的参数。
