### ISSUE TITLE
UDAF 执行过程

### ISSUE THREAD

**Issue by hengshanji** [aliyun/aliyun-odps-python-sdk#37]
UDAFRunner 里面看到udaf是将所有数据均分为两份，分别放到buffer0 buffer1 里面。在merge函数里合并这两个buffer。但是我发现实际上，可能所有数据都在一个buffer里面。导致数据错误

我是做一个将string合并的函数。输入n个string。输出是n个string的依次首位相连的string。
下面是代码。
@annotate('string->string')
class array2string(BaseUDAF):
    def new_buffer(self):
        return list()
    def iterate(self, buffer, unit):
        buffer.append(unit)
    def merge(self, buffer, pbuffer):
        if len(buffer) == 0:
            buffer.append(pbuffer[0])
            for i in range(len(pbuffer)):
                buffer.append(pbuffer[i])
                buffer.append('')

        else:
            pass
            
            for i in range(len(pbuffer)):
                if 2*i+1 < len(buffer):
                    buffer[2*i+1] = pbuffer[i]
                else:
                    pass
        	
    def terminate(self, buffer):
        return ';'.join(buffer)

**Comment by chineking** [comment]
sql 的 udaf 问题需要提工单。而不是在这里提 issue。
