### ISSUE TITLE
批量读取数据到dataframe

### ISSUE THREAD

**Issue by qbj10** [aliyun/aliyun-odps-python-sdk#39]
想将从数据库中读取大量数据到本地的csv
用odps.df接口似乎会一次读取所有数据, 导致内存不足
目前只能通过open_reader() 读取
有更好的办法吗?

**Comment by chineking** [comment]
我们有计划在未来改造 PyODPS DataFrame 不一次性加载。

但现在只能用 open_reader 读取，实际上通过 csv 标准库写也不是很麻烦。

**Comment by wjsi** [comment]
Arrow tunnel can be used to read data in batches.
