### ISSUE TITLE
to_pandas报错

### ISSUE THREAD

**Issue by aabbiiL** [aliyun/aliyun-odps-python-sdk#43]
ODPSError: InstanceId: 20171221102131257g9c5vlu
ODPS-0130071:[0,0] Semantic analysis exception - INT type is not enabled in current mode
ODPS-0130071:[0,0] Semantic analysis exception - INT type is not enabled in current mode

**Comment by chineking** [comment]
这个实际上应该是没打开 MaxCompute 的 hive 类型兼容选项。

升级到新版，然后设置选项：

```
from odps import options

options.sql.use_odps2_extension = True
```

然后重跑试下
