### ISSUE TITLE
读取表的总数据量除了执行SQL还有其他方法吗？

### ISSUE THREAD

**Issue by Lovecanon** [aliyun/aliyun-odps-python-sdk#45]
现在我想统计每张表的数据量，在table对象或partition对象上并没有这个属性，请问除了使用SQL的count(*)还有其他方法吗？

**Comment by chineking** [comment]
不查询是没法知道数据的条数的。table 或者 partition 上有个属性 `size` ，是表示物理存储量。

**Comment by Lovecanon** [comment]
谢谢啦，
