### ISSUE TITLE
有没有类似pandas的 loc 和 iloc 接口，可以访问DataFrame的行列？

### ISSUE THREAD

**Issue by thesby** [aliyun/aliyun-odps-python-sdk#46]

**Comment by chineking** [comment]
取列通过偏移可以 

```python
df[df.schema.names[i]]
```

取行是不可以的，因为 MaxCompute 上数据存储是不保证有序的，所以我没法取对应第几行的数据。

你可以把部分数据  to_pandas 来操作。

**Comment by thesby** [comment]
如果不管行号，只需要按行迭代就行了呢？有没有这样的操作？

**Comment by chineking** [comment]
你是想按行 apply 一个 function？

开通 python udf 吧

**Comment by siyuwj** [comment]
No updates, close first.
