### ISSUE TITLE
使用DataFrame中的join操作，会产生临时文件，但是它写的位置我没有权限，这个位置怎么改啊？

### ISSUE THREAD

**Issue by thesby** [aliyun/aliyun-odps-python-sdk#48]
```
data = data_1.join(data_2, on='id', how='left').to_pandas()
```
这里会需要写一个临时文件，但是默认的写入位置我没有权限，请问怎么修改这个写入位置啊？
OSError: [Errno 13] Permission denied: '/home/xxx/.pyodps/tempobjs/default/0077c4bac21ef5d6fd61e15d41dbcfek'

**Comment by chineking** [comment]
这个路径用来清除临时表的。可以通过设置环境变量修改。在运行前通过修改

```
import os

os.environ['PYODPS_DIR'] = 'your_dir_path'
```

设置成你有权限的路径即可。

**Comment by thesby** [comment]
恩，谢谢！
