### ISSUE TITLE
怎么将reader转化为dataframe

### ISSUE THREAD

**Issue by NYcleaner** [aliyun/aliyun-odps-python-sdk#51]
你好请问下，比如我根据table和partition（partition是每天）得到reader，如何将这个reader转化为dataframe，谢谢
`reader = table.open_reader(partition=‘20180110’)`

**Comment by NYcleaner** [comment]
目前找的方法是将reader转化为一张新table，然后再创建，不过这样太麻烦

**Comment by chineking** [comment]
refer to #31 

please check the closed issue before post a new one

**Comment by chineking** [comment]
to_pandas 有个害处是数据拉到本地了，如果要直接创建 PyODPS DataFrame，确实需要先转化为表

**Comment by chineking** [comment]
推荐使用分区表，下次使用 df 的时候从表分区创建。

**Comment by NYcleaner** [comment]
哇，这个可以，很nice
