### ISSUE TITLE
pyodps，writer.write(records)出错

### ISSUE THREAD

**Issue by liusunpan** [aliyun/aliyun-odps-python-sdk#52]
一次性插入数据报错，
odps.models.table，line 476, in write
IndexError：list index out of range

**Comment by liusunpan** [comment]
with t.open_writer(partition='p_date=%s'% self.now_date_format,create_partition=True ) as writer:
            writer.write(records)
这段出错了，升级到最新的opds模块是否能解决。

**Comment by chineking** [comment]
先升级试下。

**Comment by liusunpan** [comment]
恩，升级了。之前跑了两天，第3天报这个错误

**Comment by chineking** [comment]
把新的错误栈贴下。

**Comment by liusunpan** [comment]
最早是一次插入一行，效率感觉低。改成一次性插入后跑了2天就出这个问题

**Comment by liusunpan** [comment]
新的刚部署，等几天看看

**Comment by liusunpan** [comment]
升级最新的模块，跑了2天还是报这个错误
odps.models.table，line 565, in write
IndexError：list index out of range

**Comment by chineking** [comment]
564                    elif isinstance(arg, (list, tuple)):
565                        if isinstance(arg[0], Record):

所以你觉得会是什么错误呢，很显然你传进来的 list 里面是空的，这怎么可能写的对

**Comment by liusunpan** [comment]
恩，我在看看吧，怎么会传入为空[]

**Comment by chineking** [comment]
本质上你可以写 
```
[
  [0, 'a']
  [1, 'b']
]
```
这样一次性写入多条，应该有的没有数据写入。应该把这些过滤掉
