### ISSUE TITLE
怎么打包有odps模块的py文件？

### ISSUE THREAD

**Issue by aabbiiL** [aliyun/aliyun-odps-python-sdk#53]
pyinstaller -F xxx.py成功了 
但是运行exe后报错
No such file or directory: 'C:\\Users\\ll\\AppData\\Local\\Temp\\_MEI127122\\odps\\lib\\cloudpickle.py'

**Comment by chineking** [comment]
我没有用过 pyinstaller，但我简单看了下，这个可以定义 spec 文件，然后你把 pyodps 包 include 进去吧，大概这样。

这个 issue 即将被 close，原则上和 pyodps 无关。
