### ISSUE TITLE
如何从SQL的结果生成DataFramae？

### ISSUE THREAD

**Issue by thesby** [aliyun/aliyun-odps-python-sdk#55]
我想直接从一个ODPS的SQL结果生成DataFrame，请问有这样的操作吗？

**Comment by chineking** [comment]
insert overwrite/into 或者 create table as 的 SQL 才可以从 Table 创建 DataFrame，否则没法创建。

只能全部读取从 pandas DataFrame 创建本地 PyODPS DataFrame

**Comment by thesby** [comment]
insert overwrite/into 或者 create table as 的SQL是会把数据写到表里面的吧，这样岂不是还是需要临时表

**Comment by chineking** [comment]
是需要创建，但是这个操作实际上没有什么 overhead

本来 select 语句就会有落地数据，insert 之类的无非是 meta 有条记录而已。
