### ISSUE TITLE
如何获取一定范围分区

### ISSUE THREAD

**Issue by yunair** [aliyun/aliyun-odps-python-sdk#61]
因为数据是增量的，所以需要把所有分区的数据都拿出来一起处理，
在odps上可以下`where pt > xxxxx`,
但是在代码里，因为这个判断`kv = sp.split('=')`，导致无法使用类似odps上面的方式

**Comment by chineking** [comment]
没搞懂你要干嘛。

API 里不是有取 Table 下所有分区的方法吗

**Comment by yunair** [comment]
哦哦，不选分区就可以了，谢谢
