### ISSUE TITLE
dataframe如何实现滑动窗口的操作

### ISSUE THREAD

**Issue by wyn-ying** [aliyun/aliyun-odps-python-sdk#63]
类似pandas的rolling，滑动窗口聚合做avg，sum等操作。
能想到的办法只有大量用groupby.lag/lead配合apply。但是遇到groupby的列不唯一或者滑动窗口特别宽的情况，可操作性差。
有适合的接口或更好的方案吗？

**Comment by chineking** [comment]
这个在 pyodps DataFrame 上不太好实现。原因是 MaxCompute 上数据存储实际上不保证有序。
