### ISSUE TITLE
如何使用pyodps生成key-value特征

### ISSUE THREAD

**Issue by Jonuknownothingsnow** [aliyun/aliyun-odps-python-sdk#67]
有没有比较快速的方法可以把数据转化成key-value的形式，作为稀疏特征使用？

例如把三列的用户-商铺-交易额的数据，转化成两列用户-kv_col这样，每一行是一个用户，kv_col中是该用户在所有商铺交易的记录形如（{"商铺1":"交易额","商铺2":"交易额"}

在pandas中的话可以根据用户groupby之后用to_dict做成。

在pyodps中我尝试先用pivot_table变形后再用to_kv来做出一列key-value特征，但是遇到了两个问题，一个是to_kv运行的时候导致jupyter的kernel挂掉（在ide中新建pyodps任务来执行也失败了），另一个是在维度过多时会报错提示最多允许1200列。

所以想问下有没有能够直接做这样变形的方法？
（因为project不支持python udf，所以没有办法在pyodps这边用groupby再agg自定义的方法,而且看文档python udf似乎也不支持输出dict）

**Comment by Jonuknownothingsnow** [comment]
我想到一个办法，按上面的例子，就是把商铺-交易额两列都做成字符串用“:”连在一起，然后再groupby之后用cat(sep=",")拼起来，这样相当于每个用户对应一个“商铺1:交易额,商铺2:交易额"的字符串，这样给它标注为稀疏字段之后，pyodps的模型能识别出来吗

**Comment by chineking** [comment]
其实这个需求用 df.apply(func, axis=1) 是比较简单的，我推荐你可以申请开通 Python UDF，会比较方便。

至于机器学习能不能用这个可能需要确认下。

**Comment by Jonuknownothingsnow** [comment]
机器学习应该是支持这个的吧，我看文档里有写可以标注一列为KV列再使用。PythonUDF我之后看看怎么找主账号申请，不开的话感觉很多东西写出来，太难受了。发现列运算里的很多字符串方法也依赖PythonUDF是吗？刚刚试了replace、upper这些都报错说项目不支持Python UDF。

**Comment by chineking** [comment]
有些操作内部实现是用了自定义函数，就像你说的 replace，不过 upper 应该没有吧。

总之，开通 Python UDF，灵活性上会有极大提升，一下子能做的事情就太多了。
