### ISSUE TITLE
write_table 如何传入 generator

### ISSUE THREAD

**Issue by einvince** [aliyun/aliyun-odps-python-sdk#69]
o.write_table('test_table', records, partition='pt=test', create_partition=True)

我们建议在使用 write_table 方法时，一次性写入多组数据， 或者传入一个 generator 对象

---------------
要写的数据太多，想提高效率，文档里的 generator 具体如何实现，能举个简单例子吗，谢谢🙏

**Comment by chineking** [comment]
```
def gen_data():
    with open(file_name) as f:
        for line in f:
            yield table.new_record(line.split())
```

就是生成器而已。
