### ISSUE TITLE
python setup.py install ERROR

### ISSUE THREAD

**Issue by lijingpeng** [aliyun/aliyun-odps-python-sdk#7]
python setup.py install
  File "setup.py", line 118
    with open('requirements.txt') as f:
            ^
SyntaxError: invalid syntax

**Comment by chineking** [comment]
Python版本太老了，连with都不支持，应该是<=2.4的版本。

我们需要2.7+或者3.3+

**Comment by lijingpeng** [comment]
正解，集团部分开发机重装操作系统居然默认Python 2.4版本，也是醉了
