### ISSUE TITLE
文档里移除了机器学习相关的章节？

### ISSUE THREAD

**Issue by Jonuknownothingsnow** [aliyun/aliyun-odps-python-sdk#70]
最新的文档里好像把机器学习的章节移除了？目前在使用的pyodps里的机器学习部分会受到影响吗，比如说xgboost之类的，这块之后会全部移除吗？如果是的话有没有什么替代的方案啊。

**Comment by chineking** [comment]
ml 的算法都可以通过 run_xflow 来调用，参考文档：

http://pyodps.readthedocs.io/zh_CN/latest/base-models-zh.html#id1

**Comment by Jonuknownothingsnow** [comment]
好的，这个xflow我理解是不是就相当于datawork里那个pai平台啊

**Comment by chineking** [comment]
run_xflow 等同于跑 pai 命令，而 pai 平台上的节点背后也是调的 pai 命令。

**Comment by Jonuknownothingsnow** [comment]
所以o.run_xflow('AlgoName'）这里的AlgoName是我在pai平台上创建的一个"实验"？还是pai平台上的一个"组件"?因为之前用pai平台的时候接触的都是它那个图形的界面，不是很了解pai 命令里面参数的含义，也没找着pai 命令的文档什么的_(:з」∠)_

**Comment by chineking** [comment]
这个你要找别的人问了。问 pai 的同学或者之类的，抱歉这里不做解答。
