### ISSUE TITLE
本地测试无法进行

### ISSUE THREAD

**Issue by kanonlemon** [aliyun/aliyun-odps-python-sdk#74]
运行报错：

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\odps\Scripts\pyou", line 51, in <module>
    main()
  File "C:\ProgramData\Anaconda3\envs\odps\Scripts\pyou", line 38, in main
    usermod = __import__(pkg, globals(), locals(), [name,], -1)
ValueError: level must be >= 0

附加问题：
warehouse 里面也没有下载的的是数据

运行环境：
windows10
python env 3.6
intell J

**Comment by kanonlemon** [comment]
现在数据下载没了问题， 但是发现pyou.py 里面这上面的代码 import 参数都是 -1， 但是最后也都抛 ValueError: level must be >= 0 的异常， 请说一下问题所在

**Comment by chineking** [comment]
因为 MaxCompute 环境，只支持 Python 2.7，故 pyou 这个本地测试工具只支持 Python 2.7。

但 pyodps 本身是同时支持 2 和 3 的。要使用 pyou 请用 python 2.7 版本
