### ISSUE TITLE
Logview地址不对，打开后显示Invalid End Point

### ISSUE THREAD

**Issue by zhengwx11** [aliyun/aliyun-odps-python-sdk#78]
Logview网址和其他途径拿到的域名就不一样。
正常打开的是这样的：` http://logview.odps.aliyun.com/logview/?h=http://service.odps.aliyun-inc.com/`
打不开的是这样的：` http://logview.odps.aliyun.com/logview/?h=http://service-corp.odps.aliyun-inc.com/`

手动修正后还是一样，应该是token里边有些东西要变。
我是内网用户，也许是这个原因？

**Comment by chineking** [comment]
内网用户请不要在这里提问。安装内部版本解决。
