### ISSUE TITLE
私有云用户 交互式体验增强问题

### ISSUE THREAD

**Issue by CoralLeiCN** [aliyun/aliyun-odps-python-sdk#79]
使用的环境是阿里私有云。
Jupyter Nobotbook下结果探索功能没有显示，没有进度条显示
运行时在anaconda cmd 显示如下信息
![capture123](https://user-images.githubusercontent.com/19520698/43876253-cd8eeed6-9bc6-11e8-973f-f856443a2dd7.PNG)

**Comment by chineking** [comment]
参考：https://yq.aliyun.com/articles/277333?spm=a2c4e.11155435.0.0.8da03312a8EpDL 第9条

**Comment by CoralLeiCN** [comment]
尝试第9条会报错，是不是pyodps nbextension安装失败了?
![pyodps](https://user-images.githubusercontent.com/19520698/44073782-3099b5b0-9fc8-11e8-9aec-630f131488a2.PNG)
