### ISSUE TITLE
对数据求最大值（或最小值）后的数据不能直接用于计算

### ISSUE THREAD

**Issue by zemelLeong** [aliyun/aliyun-odps-python-sdk#82]
分别从两个数据表中取出数据，从一个表中取出最大值、最小值和另一个表做计算，报错如下
![image](https://user-images.githubusercontent.com/26835087/46010924-db633580-c0f6-11e8-8433-043d7c5b5147.png)
然后分别对最大值和最小值做如下操作后就能正常计算了
![image](https://user-images.githubusercontent.com/26835087/46011032-2f6e1a00-c0f7-11e8-8a3e-c39d0b2ebeb0.png)

**Comment by chineking** [comment]
哦，这个是 by design 的，你的最小值、最大值是通过 df2 算出来的，然后拿这个值去和 df1 计算，这个不是合法的。

在 pyodps DataFrame 的范畴，两个 df 之间要计算，必须要经过 join、union 等操作。此外，PyODPS DataFrame 是 lazy 计算的，当真正计算的时候，会检查所有的输入 df，如果来源不同，这个时候就不合法了。

所以，你确实需要先触发 min 和 max 的计算，也就是

**Comment by zemelLeong** [comment]
请问怎样触发它计算呢，通过调用head方法好像不太合适

**Comment by chineking** [comment]
```
min_val.execute()
```

通过 execute 手动触发标量值的计算。

**Comment by zemelLeong** [comment]
谢谢
