### ISSUE TITLE
如何在建表时指定字段是否允许空

### ISSUE THREAD

**Issue by xjr7670** [aliyun/aliyun-odps-python-sdk#85]
如题。

我看了官方文档，也用了搜索，都没有发现能实现建表时指定字段是否允许空的设置。
同时我也看了源码中的Schema和Column这两个类的实现部分，也没有发现有相关的配置，
请问下是SDK中没有实现这个功能呢，还是怎么样的。

还望告知，谢谢！

**Comment by chineking** [comment]
duplicate #84
