### ISSUE TITLE
dataframe写入表失败提示Should invoke like odps.write_table(block_id, records, block_id2, records2, ..., **kw)

### ISSUE THREAD

**Issue by tsiens** [aliyun/aliyun-odps-python-sdk#86]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-82-964610d4bab3> in <module>()
----> 1 s.write_table(score_table, result, partition='%s=%s'%(orig_dt,dt), create_partition=True)

E:\Anaconda3\lib\site-packages\odps\core.py in write_table(self, name, *block_records, **kw)
    362 
    363             if len(blocks) != len(records_iterators):
--> 364                 raise ValueError('Should invoke like '
    365                                  'odps.write_table(block_id, records, block_id2, records2, ..., **kw)')
    366 

ValueError: Should invoke like odps.write_table(block_id, records, block_id2, records2, ..., **kw)

result的数据类型为odps.df.expr.collections.RowAppliedCollectionExpr
测试result为list则成功
请问如何写入表？

**Comment by chineking** [comment]
write_table 不支持写 dataframe。
