### ISSUE TITLE
在使用 persist 时。出现 Too many open files 的报错

### ISSUE THREAD

**Issue by xiaoliwang** [aliyun/aliyun-odps-python-sdk#88]
odps.errors.ScriptError: ODPS-0123055: InstanceId: 20181108132420895gr8oz3pr2
ODPS-0123055:Script exception - Traceback (most recent call last):
  File "/home/admin/pyodps_udf_1541683460_97f72e19_8dfe_40eb_bb22_bf67af788196.py", line 2636, in __init__
    f = get_cache_archive(lib)
  File "/home/admin/lib/python/odps/distcache.py", line 229, in get_cache_archive
    return [open(i, 'r') for i in ret_files]
IOError: [Errno 24] Too many open files: '/apsara/odps/sharedcache/sound_recommend_test/archive/5BE433EABC21375169016B9F_pandas.zip/files/./pandas/tests/io/msgpack/test_newspec.py'

**Comment by wjsi** [comment]
Already fixed.
