### ISSUE TITLE
使用list_volume_files 得到 VolumnFile 的一个list后怎么知道每个VolumnFile 的size

### ISSUE THREAD

**Issue by bibabolynn** [aliyun/aliyun-odps-python-sdk#92]
node_files = odps.list_volume_files(volume_path + '/' + config_phstore['node_project'])
 for each_file in node_files:
            if os.path.isfile(each_file):
                node_file_size += os.path.getsize(each_file)
                logger.error("node file size:" + str(node_file_size))

在运行到if语句的时候报错 TypeError: coercing to Unicode: need string or buffer, VolumeFile found
我要怎么才能获取到一个路径下的每个 file的大小呢？
因为不知道要在哪儿提问，所以在这儿提问了，如果地方不对的话请告知一下去哪里提问，谢谢

**Comment by chineking** [comment]
目前拿不到 size。
