### ISSUE TITLE
使用func接口调用odps内置函数报错: 'Func' object has no attribute 'node_name'

### ISSUE THREAD

**Issue by ekayxu** [aliyun/aliyun-odps-python-sdk#94]
![image](https://user-images.githubusercontent.com/239437/56893642-f2676d00-6ab5-11e9-9f5a-086d20e38665.png)

**Comment by chineking** [comment]
1. PyODPS 支持字符串直接相加，`(v.a + '_' + v.b).rename('a_b')`
2. 如果一定要用 func，rename 下，或者 `func.xxx(***, name='new_name')` 试下
