### ISSUE TITLE
log_view_host应该跟着  ODPS 类

### ISSUE THREAD

**Issue by albin3** [aliyun/aliyun-odps-python-sdk#96]
如题，

目前log_view_host 取的是options中的值，目前遇到的场景：  本地同时连接专有云、公共云odps，此时两个环境的logview地址不同。而options中只能存储一个log_view_host导致用起来很不方便。

https://github.com/aliyun/aliyun-odps-python-sdk/blob/39dd4db5bbd9fca2e884e7e3768b521435ff0225/odps/core.py#L1758

**Comment by qinxuye** [comment]
这个是的。这个你有兴趣改了提一个 pull request 么？

**Comment by qinxuye** [comment]
这个是的。这个你有兴趣改了提一个 pull request 么？

**Comment by albin3** [comment]
@qinxuye pr已经提了，麻烦关注下。

**Comment by albin3** [comment]
@qinxuye 测试完了么？

**Comment by wjsi** [comment]
Resolved in the latest release.
